version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '16379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  api:
    container_name: spam-comment-api
    build:
      dockerfile: Dockerfile
      target: production
    image: spam-comment-api
    depends_on:
      - cache
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    links:
      - cache
    volumes:
      - ./:/src
volumes:
  cache:
    driver: local