GET / HTTP/1.1
host: {{host}}

###

GET /api/v1/health HTTP/1.1
host: {{host}}

###

POST /api/v1/comments HTTP/1.1
user: 1
host: {{host}}
Content-Type: application/json

{"comment": "different same message"}

###

GET /api/v1/comments HTTP/1.1
host: {{host}}
